# Generated by Django 5.0 on 2023-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcard',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AddField(
            model_name='productcard',
            name='buffet',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Buffet'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='building',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Residencia'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='button',
            field=models.URLField(blank=True, null=True, verbose_name='Reservar'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='pets',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mascotas'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estadía'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(upload_to='plans', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre Plan'),
        ),
    ]
