# Generated by Django 5.0 on 2023-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_productcard_options_productcard_buffet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='button',
        ),
    ]
